[package]
name = "embassy-template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-stm32 = { version = "0.1.0", git="https://github.com/embassy-rs/embassy.git", features = ["nightly", "unstable-traits", "unstable-pac", "memory-x", "time-driver-any", "exti", "embedded-sdmmc", "chrono"]  }
embassy-sync = { version = "0.2.0", git="https://github.com/embassy-rs/embassy.git",  features = [] }
embassy-executor = { version = "0.3.0", git="https://github.com/embassy-rs/embassy.git", features = ["nightly", "executor-thread", "executor-interrupt", "integrated-timers"] }
embassy-time = { version = "0.1.2", git="https://github.com/embassy-rs/embassy.git", features = ["unstable-traits", "tick-hz-32_768"] }

defmt = "0.3"
defmt-rtt = "0.4"

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }
static_cell = { version = "1.1", features = ["nightly"]}

[features]
default = ["defmt", "f407ve"]
defmt = [
"embassy-executor/defmt",
"embassy-time/defmt",
"embassy-time/defmt-timestamp-uptime",
"embassy-stm32/defmt",
]
f407ve = ["embassy-stm32/stm32f407ve", "embassy-executor/arch-cortex-m"]
